import React from "react";
import "./css/styles.css";
import { Metadata } from "next";
import Link from "next/link";
export const metadata: Metadata = {
  title: {
    default: "Kevin Victor Lepiten - Next JS Resume",
    template: "%s | Kevin Lepiten Resume Next JS project ",
  },
  description: "Generated by Kevin/Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i&display=optional"
          rel="stylesheet"
          type="text/css"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700&display=optional"
          rel="stylesheet"
          type="text/css"
        />
        <script
          src="https://use.fontawesome.com/releases/v6.1.0/js/all.js"
          defer
        ></script>
      </head>
      <body id="page-top">
        <nav
          className="navbar navbar-expand-lg navbar-dark bg-primary fixed-top"
          id="sideNav"
        >
          <a className="navbar-brand js-scroll-trigger" href="#page-top">
            <span className="d-block d-lg-none">Kevin Victor Lepiten</span>
            <span className="d-none d-lg-block">
              <img
                className="img-fluid img-profile rounded-circle mx-auto mb-2"
                src="/img/profile.jpg"
                alt="Kevin Lepiten"
              />
            </span>
          </a>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarResponsive">
            <ul className="navbar-nav">
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/">
                  About
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/experience">
                  Experience
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/education">
                  Education
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/skills">
                  Skills
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/interests">
                  Interests
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/portfolio">
                  Portfolio
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/awards">
                  Awards
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link js-scroll-trigger" href="/myblog">
                  Blog
                </Link>
              </li>
            </ul>
          </div>
        </nav>
        <div className="container-fluid p-0">{children}</div>
      </body>
    </html>
  );
}
